-- ===== Catalyst Core: The 13th Hour — shared block =====
-- Generated by tabletop/forge.py from game.spec.json.
-- Edit tabletop/lua/ + the spec, never build/ output.

{{FORGE:DATA}}

function ccElem(name)
  if name == nil then return nil end
  local n = string.lower(tostring(name))
  for _, e in ipairs(CC.elements) do
    if string.lower(e.name) == n then return e end
  end
  return nil
end

function ccTier(t)
  for _, row in ipairs(CC.tiers) do
    if row.tier == t then return row end
  end
  return CC.tiers[1]
end

function ccTotal(pool)
  local n = 0
  for _, v in pairs(pool or {}) do n = n + (tonumber(v) or 0) end
  return n
end

function ccFmtPool(pool)
  local parts = {}
  for _, e in ipairs(CC.elements) do
    local v = (pool or {})[e.name]
    if v ~= nil and v ~= 0 then table.insert(parts, e.name .. " " .. v) end
  end
  if #parts == 0 then return "empty" end
  return table.concat(parts, " | ")
end

-- Every scripted object is generic + flexible: its config comes from its
-- GM Notes as JSON, merged over the given defaults. Repurpose any object
-- in-game by editing GM Notes, no Lua required.
function ccNotesConfig(defaults)
  local cfg = {}
  for k, v in pairs(defaults or {}) do cfg[k] = v end
  local notes = self.getGMNotes()
  if notes ~= nil and notes ~= "" then
    local ok, parsed = pcall(function() return JSON.decode(notes) end)
    if ok and type(parsed) == "table" then
      for k, v in pairs(parsed) do cfg[k] = v end
    end
  end
  return cfg
end

-- Buttons in scale-compensated local space: the same template works on an
-- object of any scale (the "generic shapes" promise).
function ccBtn(p)
  local s = self.getScale()
  p.function_owner = self
  p.position = { p.position[1] / s.x, p.position[2] / s.y, p.position[3] / s.z }
  p.rotation = p.rotation or { 0, 180, 0 }
  local fw = (p.width == 0 and p.height == 0)  -- width 0 + height 0 = pure label
  p.width = fw and 0 or math.max(1, math.floor((p.width or 320) / s.x))
  p.height = fw and 0 or math.max(1, math.floor((p.height or 320) / s.z))
  p.font_size = math.max(1, math.floor((p.font_size or 120) / s.x))
  self.createButton(p)
end

function ccEnsureTag(tag)
  if not self.hasTag(tag) then self.addTag(tag) end
end
