"""fence/render_codex.py - render the fence registry into the .codex/ layer.

The pen for the Codex surface (done-line 0027): reads fence/policy.py
and emits, deterministically,

- .codex/rules/ontum.rules   the firm denials as native prefix_rule
                             entries (Starlark; Codex validates the
                             inline match/not_match examples at load)
- .codex/hooks.json          the ambient summons: SessionStart and
                             UserPromptSubmit run `python -m
                             loop.summon --hook`, the same briefing a
                             Claude session is handed

Outputs are committed but never hand-edited - tests/test_fence.py
refuses a stale render. Codex loads the layer only once the project is
trusted; hooks additionally need a one-time review via /hooks.

Stdlib only. Run from the repo root: python fence/render_codex.py
"""

import json
import pathlib

try:
    from . import policy
except ImportError:  # run as a script: fence/ is sys.path[0]
    import policy

ROOT = pathlib.Path(__file__).resolve().parents[1]
RULES_OUT = ROOT / ".codex" / "rules" / "ontum.rules"
HOOKS_OUT = ROOT / ".codex" / "hooks.json"

SUMMON = "python -m loop.summon --hook"

HOOKS = {
    "hooks": {
        "SessionStart": [
            {
                "hooks": [
                    {
                        "type": "command",
                        "command": SUMMON,
                        "timeout": 30,
                        "statusMessage": "ontum: open summons",
                    }
                ]
            }
        ],
        "UserPromptSubmit": [
            {
                "hooks": [
                    {
                        "type": "command",
                        "command": SUMMON,
                        "timeout": 30,
                    }
                ]
            }
        ],
    }
}


def _element(value):
    """One pattern element as Starlark: a literal or a union list."""
    if isinstance(value, tuple):
        return "[" + ", ".join(json.dumps(v) for v in value) + "]"
    return json.dumps(value)


def _examples(name, values):
    lines = [f"    {name} = ["]
    lines.extend(f"        {json.dumps(v)}," for v in values)
    lines.append("    ],")
    return lines


def render_rules():
    lines = [
        "# .codex/rules/ontum.rules - generated by fence/render_codex.py;"
        " never hand-edit.",
        "# The registry is fence/policy.py (done-line 0027); edit there"
        " and re-render:",
        "#     python fence/render_codex.py",
        "# Test a command against this file:",
        "#     codex execpolicy check --pretty --rules"
        " .codex/rules/ontum.rules -- git add .",
        "",
    ]
    for rule in policy.RULES:
        pattern = ", ".join(_element(e) for e in rule["argv"])
        lines.append("prefix_rule(")
        lines.append(f"    pattern = [{pattern}],")
        lines.append(f"    decision = {json.dumps(rule['decision'])},")
        lines.append(
            f"    justification = {json.dumps(rule['justification'])},")
        lines.extend(_examples("match", rule["match"]))
        lines.extend(_examples("not_match", rule["not_match"]))
        lines.append(")")
        lines.append("")
    return "\n".join(lines)


def render_hooks():
    return json.dumps(HOOKS, indent=2) + "\n"


def main():
    RULES_OUT.parent.mkdir(parents=True, exist_ok=True)
    RULES_OUT.write_text(render_rules(), encoding="utf-8", newline="\n")
    HOOKS_OUT.write_text(render_hooks(), encoding="utf-8", newline="\n")
    count = len(policy.RULES)
    print(
        f"result: done - rendered {RULES_OUT.relative_to(ROOT).as_posix()} "
        f"({count} rules) and {HOOKS_OUT.relative_to(ROOT).as_posix()}"
    )


if __name__ == "__main__":
    main()
